# Site settings
title: Daryl Robbins
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my homepage. There is more coming soon!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: darylrobbins
github_username:  darylrobbins
contact_link: https://darylrobbins.wufoo.com/forms/contact-form/
analytics:
  google: 
      tracking_id: 'UA-39643890-2'

# Build settings
markdown: kramdown
